package com.classroom.wnn.model;

import java.io.Serializable;

public class BaseUserBean implements Serializable {
	/********************************************
	 * BaseUserBean.java<br>
	 * 字段详细描述……<br>
	 * @since v1.0.0
	 * <br>
	 * --------------------------------------<br>
	 * 编辑历史<br>
	 * 2015年6月12日::x04::创建此字段<br>
	 *********************************************/
	private static final long serialVersionUID = 900393301574745415L;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_cm_user.ID
	 *
	 * @mbggenerated Mon Oct 06 13:36:45 CST 2014
	 */
	private Integer id; //id

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_cm_user.YHBH
	 *
	 * @mbggenerated Mon Oct 06 13:36:45 CST 2014
	 */
	private String yhbh; //用户编号

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_cm_user.YHMC
	 *
	 * @mbggenerated Mon Oct 06 13:36:45 CST 2014
	 */
	private String yhmc; //用户名称

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_cm_user.MM
	 *
	 * @mbggenerated Mon Oct 06 13:36:45 CST 2014
	 */
	private String mm; // 密码

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_cm_user.YHLX
	 *
	 * @mbggenerated Mon Oct 06 13:36:45 CST 2014
	 */
	private String yhlx; //用户类型

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_cm_user.LP
	 *
	 * @mbggenerated Mon Oct 06 13:36:45 CST 2014
	 */
	private String lp; //上次登录ip

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_cm_user.ID
	 *
	 * @return the value of t_cm_user.ID
	 *
	 * @mbggenerated Mon Oct 06 13:36:45 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_cm_user.ID
	 *
	 * @param id the value for t_cm_user.ID
	 *
	 * @mbggenerated Mon Oct 06 13:36:45 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_cm_user.YHBH
	 *
	 * @return the value of t_cm_user.YHBH
	 *
	 * @mbggenerated Mon Oct 06 13:36:45 CST 2014
	 */
	public String getYhbh() {
		return yhbh;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_cm_user.YHBH
	 *
	 * @param yhbh the value for t_cm_user.YHBH
	 *
	 * @mbggenerated Mon Oct 06 13:36:45 CST 2014
	 */
	public void setYhbh(String yhbh) {
		this.yhbh = yhbh;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_cm_user.YHMC
	 *
	 * @return the value of t_cm_user.YHMC
	 *
	 * @mbggenerated Mon Oct 06 13:36:45 CST 2014
	 */
	public String getYhmc() {
		return yhmc;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_cm_user.YHMC
	 *
	 * @param yhmc the value for t_cm_user.YHMC
	 *
	 * @mbggenerated Mon Oct 06 13:36:45 CST 2014
	 */
	public void setYhmc(String yhmc) {
		this.yhmc = yhmc;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_cm_user.MM
	 *
	 * @return the value of t_cm_user.MM
	 *
	 * @mbggenerated Mon Oct 06 13:36:45 CST 2014
	 */
	public String getMm() {
		return mm;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_cm_user.MM
	 *
	 * @param mm the value for t_cm_user.MM
	 *
	 * @mbggenerated Mon Oct 06 13:36:45 CST 2014
	 */
	public void setMm(String mm) {
		this.mm = mm;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_cm_user.YHLX
	 *
	 * @return the value of t_cm_user.YHLX
	 *
	 * @mbggenerated Mon Oct 06 13:36:45 CST 2014
	 */
	public String getYhlx() {
		return yhlx;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_cm_user.YHLX
	 *
	 * @param yhlx the value for t_cm_user.YHLX
	 *
	 * @mbggenerated Mon Oct 06 13:36:45 CST 2014
	 */
	public void setYhlx(String yhlx) {
		this.yhlx = yhlx;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_cm_user.LP
	 *
	 * @return the value of t_cm_user.LP
	 *
	 * @mbggenerated Mon Oct 06 13:36:45 CST 2014
	 */
	public String getLp() {
		return lp;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_cm_user.LP
	 *
	 * @param lp the value for t_cm_user.LP
	 *
	 * @mbggenerated Mon Oct 06 13:36:45 CST 2014
	 */
	public void setLp(String lp) {
		this.lp = lp;
	}
}